services:
  - type: web
    name: my-django-chatbot
    env: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn job_portal.wsgi:application

    postDeploy:
      - python manage.py migrate
      - python manage.py collectstatic --noinput
