services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn job_portal.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.8
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

databases:
  - name: django-db
    databaseName: django
    user: django
